dropbox/pynsot

- docs/api.rst
- docs/auth.rst
- docs/cli.rst
- docs/index.rst
- docs/python_api.rst
- pynsot/models.py
- pynsot/util.py
Documentation around the project in general went through a bit of a hardship, mostly felt around the Python API. This has mostly been mitigated the last few months and this is a step in the right direction for it.
This aims to close out issues #56, setting up for a closure of #95 
`make html && google-chrome _build/html/python_api.html`
> Adding documentation for the Python API

- pynsot/commands/callbacks.py
- pynsot/commands/cmd_devices.py
- pynsot/commands/cmd_interfaces.py
- pynsot/commands/cmd_networks.py
- requirements-dev.txt
- Commas are now valid characters and are not treated specially to
provide multiple values for a list-type Attribute.
- Attribute-values may not contain commands when performing bulk adds.
This will be addressed in a future update.
- Updated requirements-dev: ipdb==0.9.3
> Fix #88 - Bugfix when parsing attribute values containing commas

- requirements-dev.txt
- tests/test_app.py
* Bump nsot to current latest version
* Fix capitalization in `test_site_add()`
* Fix wrong network in `test_networks_subcommands()`
* 10.10.10.0/24 should be the parent network since it gets created on line 678
* Fix wrong networks in `test_networks_allocation()`
* 10.20.30.1/32 is assigned, so 10.20.30/28 should be off-limits
The cases of incorrect networks were modified based on my interpretation
of the test code. Please let me know if I'm wrong and they truly
_should_ be the old values.
> Fix tests that are broken with the latest version of NSoT

- pynsot/app.py
- pynsot/commands/cmd_interfaces.py
- tests/test_app.py
The NSoT API supports identifying most things by either their unique ID
number, or by a natural key; the natural key for interfaces being the
combination of the device's hostname and the interface's name. Example:
* Device: switch-nyc3
* Interface: Ethernet2
* Natural Key: switch-nyc3:Ethernet2
Since dropbox/nsot#253 added caching of the device hostname on the
Interface object, lookups using that natural key are much easier.
Similar to how the API overloads the ID to be either one of those
things, I've mirrored that in the CLI. It would probably be more
user-friendly to let the user do something like specify a device
with `-D` and the interface name with `-n` or something, but that
causes a conflict with `update` since it uses `-n` to update the name of
the interface.
Given that conflict, …
> Fix #125 - Support natural key when working with interfaces

- pynsot/app.py
- pynsot/commands/cmd_circuits.py
- pynsot/util.py
- requirements-dev.txt
- requirements.txt
- tests/app/test_circuits.py
- tests/fixtures/__init__.py
- tests/fixtures/circuits.py
- tests/test_util.py
Now that we have circuits in NSoT, the CLI needs to support them. This handles all the CRUD operations, as well as subcommands for list in the API: `devices`, `addresses`, and `interfaces`.
I also did a bit of refactoring of the tests to support doing set of tests per file (e.g. circuits in their own file). Since I added a set of fixtures for the Circuit tests, those went into their own file. `tests/fixtures.py` was moved to `test/fixtures/__init__.py` to support this and still maintain backwards compatibility of imports in the existing tests.
> Add support for Circuits

- docs/cli.rst
- pynsot/commands/cmd_networks.py
- tests/test_app.py
* Corrected the spelling for the ``descendants`` sub-command on Networks. The
old misspelled form of ``descendents`` will display a warning to users.
> Fix #120 - Correct spelling for Network "descendants" sub-command.

- pynsot/commands/cmd_networks.py
- requirements-dev.txt
- tests/test_app.py
This pull request should be merged alongside dropbox/nsot#256, It allows a user to pass an 
`-s/--strict-allocation` flag to the `next_network` and `next_address` actions.
> Strict allocations

- requirements-dev.txt
- requirements.txt
This is a similar change to https://github.com/dropbox/nsot/pull/265
For the `nsot` requirement, I left it at `~=1.1.0` since API
deprecations could happen if we jump too far ahead on minor versions. I
also added a minimum version of `nsot` to ensure that tests run against
a version that has the APIs we need.
Going to hold off on merging this until https://github.com/dropbox/pynsot/pull/128 is merged since I'm sure a merge conflict in `requirements-dev.txt` will happen.
> Change requirements*txt to use Compatible Release specifiers

- pynsot/app.py
- pynsot/commands/callbacks.py
- pynsot/commands/cmd_devices.py
- pynsot/commands/cmd_interfaces.py
- pynsot/commands/cmd_networks.py
- tests/app/test_circuits.py
- tests/fixtures/__init__.py
- tests/test_app.py
The use-case here is described by @jathanism in dropbox/nsot#221, where single
objects should be able to be referenced via set query for the various
subcommands on `list`, such as `next_network` on `Network` objects.
Since these subcommands operate on a single object, we set `unique=True`
in the request so that the API will return an error if the set query
returns != 1 object.
The implementation for this is done in the `list` subcommand callback,
where we were already translating from a natural key into an ID to be
given to the subcommand request. The heavy lifting is done by a new
method on `pynsot.App`.
While I was in there, I refactored the old `set_query` method to have a
better name. If this is expected to create issues with people
programatically consuming pynsot, I can undo that …
> Fix #119 - Add ability to use set queries on `list` subcommands

- requirements-dev.txt
Travis started failing due to an error when trying to install IPython
6.0.0 with Python 2.7.x:
https://travis-ci.org/dropbox/pynsot/builds/236270172
I wasn't able to reproduce it locally on my machine (Ubuntu 16.04,
Python 2.7.12, pip 9.0.1) since it for some reason sticks to IPython
5.x, but this should at least fix Travis's problem.
> Pin IPython to 5.x

- .travis.yml
- pynsot/commands/cmd_circuits.py
- pynsot/commands/cmd_devices.py
- pynsot/commands/cmd_interfaces.py
- pynsot/commands/cmd_networks.py
- pynsot/commands/types.py
- requirements-dev.txt
- setup.cfg
- tests/app/test_circuits.py
- tests/test_app.py
Requires NSoT v1.2.0
- Interfaces may now be created/updated by referencing the device
hostname or device ID
- Circuits may now be created/updated by referencing the interfaces by
natural key (slug) OR interface ID
- The visual display of Networks, Interfaces, Circuits has been updated to be
more compact/concise
- Networks
- cidr is now displayed instead of network_address/prefix_length
- parent cidr is now displayed instead of parent_id
- Interface
- name_slug is now displayed instead of device_id/name
- parent name is now displayed instead of parent_id
- Circuits
- interface slugs are now displayed instead of ID numbers
- Added a new "natural key" parameter type so that all natural key inputs are validated
- Added flake8 to Travis CI config
> Update nsot CLI to support natural key for Interfaces/Circuits

- pynsot/commands/cmd_circuits.py
- tests/app/test_circuits.py
- tests/fixtures/circuits.py
When this module was originally written I forgot to add querying when
`-q` is passed in to `nsot circuits list`. Oops. This adds that routing,
similar to the `nsot devices list` command`, as well as some tests
around some basic set queries.
Fixes #149.
> Add set queries to `nsot circuits list`

- pynsot/app.py
- tests/app/test_circuits.py
- tests/test_app.py
Changing the behavior of the `--grep` flag to include concrete fields from objects in addition to the attributes attached to the object.
This PR should solve two things:
* Alleviating a need to fix #150, since all objects have at least a couple concrete fields
* Adds some functionality that has been in conversation for a while by maintainers of PyNSoT
> Updating `-g/--grep` output to include concrete fields on objects

- docs/development.rst
Pynsot did not have a development documentation to explain the release project. I copied this section as well as the version section over to this repo. We may want to consult with [nsot's documentation page](https://github.com/dropbox/nsot/edit/develop/docs/development.rst) to see if anything else can be ported over.
> Adding a development doc to the documentation

- pynsot/commands/cmd_protocol_types.py
- pynsot/commands/cmd_protocols.py
- tests/app/test_protocol_types.py
- tests/app/test_protocols.py
- tests/fixtures/protocol_types.py
- tests/fixtures/protocols.py
These CLI options are standard across all resource types with their
`list` subcommands, but they were forgotten with the new Protocol and
ProtocolType objects.
Fixes #159
> Add --limit and --offset to Protocol and ProtocolType CLI

- CHANGELOG.rst
- pynsot/commands/cmd_networks.py
- requirements.txt
Updates pynsot to require Click 7.x now, and also updates certain subcommands with underscores in their name to explicitly use underscores.
From Click 7.0 release notes:
> Subcommands that are named by the function now automatically have the underscore replaced with a dash. If you register a function named `my_command` it becomes `my-command` in the command line interface.
> Update pynsot to be compatible with Click 7.x

- requirements-dev.txt
- setup.py
- tests/test_app.py
Replace non-py3-compatible execfile() in setup.py. We have more work to do to get to full py3 compatibility but this is a start. Verified everything still works as intended in python2. 
While I'm here, fix a failing test and hardcode attrs to 19.1.0 in requirements-dev since newer versions of this lib cause issues with pytest (https://stackoverflow.com/questions/58189683/typeerror-attrib-got-an-unexpected-keyword-argument-convert).
> [Python 3] execfile() -> exec()

- .travis.yml
- conftest.py
- pynsot/app.py
- pynsot/commands/callbacks.py
- pynsot/commands/cmd_attributes.py
- pynsot/commands/types.py
- pynsot/constants.py
- pynsot/dotfile.py
- pynsot/models.py
- pytest.ini
- requirements-dev.txt
- requirements.txt
- tests/fixtures/__init__.py
- tests/nsot_settings.py
- tests/test_dotfile.py
- tests/test_util.py
- tests/util.py
In order to unblock code depending on pynsot to move to Python3, I'm focusing on getting beta python3 support in pynsot before NSOT has been fully migrated to py3. In order to do this I need to exclude the NSOT/Django-related tests from executing in pynsot in a python 3 environment. 
I'm doing this by selectively setting the DJANGO_SETTINGS_MODULE environment variable only when running in Python 2. In Python 3, this will not be set which will cause all tests relying on Django to be skipped by py.test. 
Some other modifications were made to allow the non-django tests to pass in both py2 and py3.  I also ran python-modernize on affected files.
Finally, add Python 3.8 builds to our Travis setup.
> [Python 3] Remove NSOT Tests from py3 and make remaining tests pass in py3

- requirements.txt
For py2/py3 compatibility, ensure the python3 backport of configparser is available for python2 builds, since the 'configparser' module doesn't exist in Python 2.
> Adding configparser Python3 backport

- pynsot/constants.py
- pynsot/dotfile.py
#170 replaced the rcfile lib with configparser, but this had a side-effect of removing support for pynsotrc files anywhere other than ~/.pynsotrc. Given that we want to allow a global config in /etc/pynsotrc as well as a local one in USER_HOME, this may break existing deployments. 
This PR adds back the ability to read from a global /etc/pynsotrc file and keeps us consistent with our documentation (https://pynsot.readthedocs.io/en/latest/config.html#configuration-basics). 
Note: There still may be other .pynsotrc locations that rcfile would automatically read from that don't work anymore, however we don't plan to support those locations. Please ensure your config file is in one of these two supported locations.
> Allow for /etc/pynsotrc
